name: Build and deploy WAR app to Azure Web App - PowerWebAPP1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -f MyWebApp/pom.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  # Ensure using v4 here
        with:
          name: java-app  # Artifact name
          path: '${{ github.workspace }}/MyWebApp/target/*.war'  # Correct path to WAR file after Maven build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4  # Ensure using v4 here
        with:
          name: java-app  # Must match the name used during upload

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PowerWebAPP1'  # Correct app name
          slot-name: 'Production'   # Correct slot name
          package: '${{ github.workspace }}'  # Correct path to WAR file
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1B74C441E26C46A59963C51D8CD321BE }}
